name: 🐛 Bug Report
description: Report a bug in LinkCore Download Manager
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please search existing issues first to avoid duplicates.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part is affected?
      options:
        - App (UI / Settings)
        - Download / Engine (HTTP/FTP/BT/Magnet)
        - Installation / Update
        - Browser Extension
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: What happened? What should have happened?
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: e.g. v1.8.15 (also include your installer type if relevant)
      placeholder: v1.8.15
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: Windows 11 23H2 / macOS 15.x / Ubuntu 24.04 ...
    validations:
      required: true

  - type: dropdown
    id: arch
    attributes:
      label: CPU Architecture
      options:
        - x64
        - arm64
        - Other
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: |
        Provide logs and/or screenshots if possible.
        If you paste logs, please wrap them in code fences.

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting, please confirm:
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: I can reproduce this issue reliably with the steps provided.
          required: true
